"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Initialize environ
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'penplus.com', 'pedx.com', 'logbook.com']

# Application definition

INSTALLED_APPS = [
    "penplus.apps.PenplusConfig",
    "pedx.apps.PedxConfig",
    "logbook.apps.LogbookConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'src.middleware.domain_check.DomainCheckMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'src/templates')],  # Add shared templates directory
        'APP_DIRS': True,  # Automatically find templates in app-specific directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Default database (can be a placeholder)
        'NAME': env('PENPLUS_DB_NAME'),  # Use the Penplus database as default
        'USER': env('PENPLUS_DB_USER'),
        'PASSWORD': env('PENPLUS_DB_PASSWORD'),
        'HOST': env('PENPLUS_DB_HOST'),
        'PORT': env('PENPLUS_DB_PORT'),
    },
    'penplus': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('PENPLUS_DB_NAME'),
        'USER': env('PENPLUS_DB_USER'),
        'PASSWORD': env('PENPLUS_DB_PASSWORD'),
        'HOST': env('PENPLUS_DB_HOST'),
        'PORT': env('PENPLUS_DB_PORT'),
    },
    'pedx': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('PEDX_DB_NAME'),
        'USER': env('PEDX_DB_USER'),
        'PASSWORD': env('PEDX_DB_PASSWORD'),
        'HOST': env('PEDX_DB_HOST'),
        'PORT': env('PEDX_DB_PORT'),
    },
    'logbook': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('LOGBOOK_DB_NAME'),
        'USER': env('LOGBOOK_DB_USER'),
        'PASSWORD': env('LOGBOOK_DB_PASSWORD'),
        'HOST': env('LOGBOOK_DB_HOST'),
        'PORT': env('LOGBOOK_DB_PORT'),
    },
}

DATABASE_ROUTERS = ['src.database_router.DatabaseRouter']

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = []  # No need for STATICFILES_DIRS since static files are inside each app
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Domains for each app
PENPLUS_DOMAIN = "http://penplus.com"
PEDX_DOMAIN = "http://pedx.com"
LOGBOOK_DOMAIN = "http://logbook.com"
